# 工作流名称
name: Hexo Deploy

# 工作流触发配置
on:
  # 当master分支有push事件时 触发工作流
  push:
    branches: [ hexo ]
  pull_request:
    branches: [ hexo ]


jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.15.3
        uses: actions/setup-node@v2
        with:
          node-version: "10.15.3"
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

#jobs:
#  # job1
#  blog-ci-cd:
#    # 任务名称
#    name: Hexo blog build & deploy
#    # 设置任务执行环境
#    runs-on: ubuntu-latest # 使用最新的 Ubuntu 系统作为编译部署的环境
#    steps:
#      # 使用 checkout@2 插件拉取代码
#      #    - name: Checkout codes
#      - uses: actions/checkout@v2
#      #      with:
#      #        submodules: true
#
#      # 使用 setup-node@v1 设置 node.js 环境
#      - name: Setup node
#        uses: actions/setup-node@v2
#        with:
#          node-version: '10.15.3'
#
#      - name: Install Dependencies
#        run: |
#          npm install hexo-cli -g
#          npm install
#
#      - name: Build
#        run: |
#          hexo clean && hexo generate
#
#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
#          publish_dir: ./public

#      # 安装 Hexo 依赖
#      - name: Install hexo dependencies
#        env:
#          #设置环境变量 仓库私钥， 用来在构建完成后 推送到仓库
#          ACTION_DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
#        # 设置 ssh 私钥， 下载 hexo-cli 脚手架及相关安装包，
#        run: |
#          mkdir -p ~/.ssh/
#          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          ssh-keyscan github.com >> ~/.ssh/known_hosts
#          git config --global user.email "a1501987783@gmail.com"
#          git config --global user.name "March1995"
#          npm install -g hexo-cli
#          npm install
#
#      # 构建博客源码 并 推送推送构建产物
#      - name: Generate files
#        run: |
#          hexo clean
#          hexo generate
#          hexo deploy
